export enum CATEGORY_ART {
  PAINTING = "PAINTING",
  WORKS_ON_PAPER = "WORKS_ON_PAPER",
  EDITION = "EDITION",
  SCULPTURE = "SCULPTURE",
  OTHERS = "OTHERS",
}

export enum DETERMINED_RESULT {
  REAL_WORKS = "REAL_WORKS",
  REASSESSMENT = "REASSESSMENT",
  UNABLE_EXAMINED = "UNABLE_EXAMINED",
  REQUEST_INSPECTION = "REQUEST_INSPECTION",
}

export enum PRESERVATION_STATE {
  IN_STORAGE = "IN_STORAGE",
  LEASING = "LEASING",
  RETURNING_MID_BATCH = "RETURNING_MID_BATCH",
  RETURN_NORMAL = "RETURN_NORMAL",
}

export enum MORTGAGE_STATUS {
  NORMAL = "NORMAL",
  PROCEED_COLLATERAL = "PROCEED_COLLATERAL",
  CANCEL = "CANCEL",
}

export enum MORTGAGE_CLASSIFICATION {
  THE_RIGHT_PLEDGE = "THE_RIGHT_PLEDGE",
  PLEDGE = "PLEDGE",
}

//detail loan
export enum DEBT_REPAYMENT_CLASSIFY {
  SOURCE_MONEY = "source-money",
  NORMAL_PROFIT = "normal-profit",
  LATE_PAYMENT_INTEREST = "late-payment-interest",
  LATE_PAYMENT_INTEREST_OTHER = "late-payment-interest-other",
}
